Orbb.Admin/Areas/Countries/Controllers/DetailController.cs
using Microsoft.AspNetCore.Mvc;
using Orbb.Admin.Utility.Mvc;
using Orbb.BL.Interfaces.Customers;
using Orbb.Common.Security;
using Orbb.Data.Models.Models.Base;
using Orbb.Data.ViewModels.Models.Base;
using Orbb.Data.ViewModels.Models.Customers;
using System.Collections.Generic;

namespace Orbb.Admin.Areas.Countries.Controllers
{
    [Area("Countries")]
    [SecuredObject("Countries")]
    public class DetailController : DetailBaseController<Country, CountryVM>
    {
        private readonly ICustomerRepository _customerRepository;
        public DetailController(ICustomerRepository customerRepository) : base("Country")
        {
            modelIncludes = new[] { "AvailableLenssets", "AvailableLenssets.Supplier" };
            redirectTo = "/Countries/detail/index/{id}";
            OverviewURL = "/Countries/overview";

            _customerRepository = customerRepository;
        }

        public override CountryVM BeforeUpdate(CountryVM model)
        {
            if (model.AvailableLenssets == null)
            {
                model.AvailableLenssets = new List<LenssetVM>();
            }
            return model;
        }
        public override CountryVM AfterUpdate(CountryVM model, bool success)
        {
            _customerRepository.RemoveUnavailableLensesFromCustomers(model.Id, model.AvailableLenssets);
            return model;
        }

    }
}

Orbb.Admin/Areas/Customers/Controllers/DetailController.cs
using Microsoft.AspNetCore.Mvc;
using Orbb.Admin.Utility.Mvc;
using Orbb.BL.Interfaces.Customers;
using Orbb.Common.Security;
using Orbb.Data.Models.Models.Customers;
using Orbb.Data.ViewModels.Models.Customers;

namespace Orbb.Admin.Areas.Customers.Controllers
{
    [Area("Customers")]
    [SecuredObject("Customers")]
    public class DetailController : DetailBaseController<Customer, CustomerVM>
    {

        private readonly ICustomerRepository _customerRepository;

        public DetailController(ICustomerRepository customerRepository) : base("Customer")
        {
            modelIncludes = new[] { "UsedLenssets", "UsedLenssets.Supplier" };
            redirectTo = "/Customers/detail/index/{id}";
            OverviewURL = "/Customers/overview";
            _customerRepository = customerRepository;
        }
    }
}

Orbb.Admin/Areas/LensSuppliers/Controllers/DetailController.cs
using Microsoft.AspNetCore.Mvc;
using Orbb.Admin.Utility.Mvc;
using Orbb.BL.Interfaces.LensSuppliers;
using Orbb.Common.Security;
using Orbb.Data.Models.Models.LensSuppliers;
using Orbb.Data.ViewModels.Models.LensSuppliers;

namespace Orbb.Admin.Areas.LensSuppliers.Controllers
{
    [Area("LensSuppliers")]
    [SecuredObject("Lens Supplier")]
    public class DetailController : DetailBaseController<LensSupplier, LensSupplierVM>
    {
        private ILensSupplierRepository lensSupplierRepository;
        private const string sessionCurrentObjectKey = "Base.LensSupplierDetail";


        public DetailController(ILensSupplierRepository lensSupplierRepository) : base("LensSupplierDetail")
        {
            redirectTo = "/LensSuppliers/detail/index/{id}";
            OverviewURL = "/LensSuppliers/overview";
            this.lensSupplierRepository = lensSupplierRepository;
        }

    }
}

Orbb.Admin/Areas/Lenssets/Controllers/DetailController.cs
using AutoMapper;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using Orbb.Admin.Utility.Mvc;
using Orbb.BL.Interfaces.Lenssets;
using Orbb.Common;
using Orbb.Common.Security;
using Orbb.Data.Models.Models.Lenssets;
using Orbb.Data.ViewModels.Models;
using Orbb.Data.ViewModels.Models.Lenssets;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Orbb.Admin.Areas.Lenssets.Controllers
{
    [Area("Lenssets")]
    [SecuredObject("lens dataset")]
    public class DetailController : DetailBaseController<LensDetail, LensDetailVM>
    {
        private readonly IControlPointRepository _controlPointRepository;
        private readonly List<int> ControlPoints = new List<int>() { 1, 3, 4 };
        private readonly IMapper _mapper;

        public DetailController(IControlPointRepository controlPointRepository, IMapper mapper) : base("LensDetail")
        {
            modelIncludes = new[] { "Supplier", "CP1", "CP2", "CP3", "CP4", "CP5", 
                "CP2ToCP1List", "CP1.CpList", "CP2.CpList", "CP3.CpList", "CP4.CpList", "CP5.CpList",
                "CP1.CpTangentList", "CP2.CpTangentList", "CP3.CpTangentList", "CP4.CpTangentList", "CP5.CpTangentList", 
                "CP1.CpCurvatureList", "CP2.CpCurvatureList", "CP3.CpCurvatureList", "CP4.CpCurvatureList", "CP5.CpCurvatureList" };
            redirectTo = "/Lenssets/detail/index/{id}";
            OverviewURL = "/Lenssets/overview";
            _controlPointRepository = controlPointRepository;
            _mapper = mapper;
        }

        /*grid methods*/
        override
        public LensDetailVM AfterLoad(LensDetailVM model, string extraData = null, bool isCopy = false)
        {
            PopulateSessionStorage(model);
            if (model.CP1 != null && model.CP1.CalculationMethod == Enumerations.CpCalculationMethod.CurvatureDesign)
            {
                foreach (var curvatureItem in model.CP1.CpCurvatureList)
                {
                    curvatureItem.CalculateSagitta(model.CP1.CurvatureDiameters);
                }
            }

            if (model.CP2 != null && model.CP2.CalculationMethod == Enumerations.CpCalculationMethod.CurvatureDesign)
            {
                foreach (var curvatureItem in model.CP2.CpCurvatureList)
                {
                    curvatureItem.CalculateSagitta(model.CP2.CurvatureDiameters);
                }
            }

            if (model.CP3 != null && model.CP3.CalculationMethod == Enumerations.CpCalculationMethod.CurvatureDesign)
            {
                foreach (var curvatureItem in model.CP3.CpCurvatureList)
                {
                    curvatureItem.CalculateSagitta(model.CP3.CurvatureDiameters);
                }
            }

            if (model.CP4 != null && model.CP4.CalculationMethod == Enumerations.CpCalculationMethod.CurvatureDesign)
            {
                foreach (var curvatureItem in model.CP4.CpCurvatureList)
                {
                    curvatureItem.CalculateSagitta(model.CP4.CurvatureDiameters);
                }
            }

            if (model.CP5 != null && model.CP5.CalculationMethod == Enumerations.CpCalculationMethod.CurvatureDesign)
            {
                foreach (var curvatureItem in model.CP5.CpCurvatureList)
                {
                    curvatureItem.CalculateSagitta(model.CP5.CurvatureDiameters);
                }
            }

            return model;
        }
        override
        public LensDetailVM BeforeUpdate(LensDetailVM model)
        {
            model.Cleanup();

            if (model.CP4.DisplayLandingZoneStepType.Equals(Enumerations.DisplayLandingZoneStepType.Microns))
            {
                ModelState["CP4.DisplayLandingZoneCenter"].Errors.Clear();
                ModelState.Remove("CP4.DisplayLandingZoneCenter");
            }

            if (model.IsDraft)
            {
                ModelState.Clear();
            }

            if (!model.UseCP1)
            {
                model.CP1Id = null;
                model.CP1 = null;
                foreach (var name in ModelState.Keys.Where(k => k.Contains("CP1.")))
                {
                    ModelState.Remove(name);
                }
            }
            if (!model.UseCP2)
            {
                model.CP2Id = null;
                model.CP2 = null;
                foreach (var name in ModelState.Keys.Where(k => k.Contains("CP2.")))
                {
                    ModelState.Remove(name);
                }
            }
            if (!model.UseCP3)
            {
                model.CP3Id = null;
                model.CP3 = null;
                foreach (var name in ModelState.Keys.Where(k => k.Contains("CP3.")))
                {
                    ModelState.Remove(name);
                }
            }
            if (!model.UseCP4)
            {
                model.CP4Id = null;
                model.CP4 = null;
                foreach (var name in ModelState.Keys.Where(k => k.Contains("CP4.")))
                {
                    ModelState.Remove(name);
                }
            }
            if (!model.UseCP5)
            {
                model.CP5Id = null;
                model.CP5 = null;
                foreach (var name in ModelState.Keys.Where(k => k.Contains("CP5.")))
                {
                    ModelState.Remove(name);
                }
            }

            PopulateModelFromSessionStorage(model);

            return model;
        }

        [AcceptVerbs("Post")]
        public JsonResult ListItems_Update([DataSourceRequest] DataSourceRequest request, [Bind(Prefix = "models")]ICollection<CPListItemVM> listItems, int cpNum)
        {
            string sessionKeyString = GenerateSessionKey(cpNum, Enumerations.CpCalculationMethod.List.ToString());
            foreach (var listItem in listItems)
            {
                var sessionKey = GetSessionKey(sessionKeyString, listItem.Id);
                this.SessionStorage.Set(sessionKey, listItem);
            }

            return Json(listItems.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs("Post")]
        public JsonResult ListItems_Create([DataSourceRequest] DataSourceRequest request, [Bind(Prefix = "models")]ICollection<CPListItemVM> listItems, int cpNum)
        {
            int counter = -1;
            string sessionKeyString = GenerateSessionKey(cpNum, Enumerations.CpCalculationMethod.List.ToString());
            foreach (var listItem in listItems)
            {
                listItem.Id = int.Parse($"-{cpNum}{-counter}");
                counter--;
                var sessionKey = GetSessionKey(sessionKeyString, listItem.Id);
                this.SessionStorage.Set(sessionKey, listItem);
            }
            return Json(listItems.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs("Post")]
        public JsonResult ListItems_Destroy([DataSourceRequest] DataSourceRequest request, [Bind(Prefix = "models")]ICollection<CPListItemVM> listItems, int cpNum)
        {
            string sessionKeyString = GenerateSessionKey(cpNum, Enumerations.CpCalculationMethod.List.ToString());
            foreach (var listItem in listItems)
            {
                var sessionKey = GetSessionKey(sessionKeyString, listItem.Id);
                this.SessionStorage.Remove(sessionKey);
            }
            return Json(listItems.ToDataSourceResult(request, ModelState));
        }
        [AcceptVerbs("Post")]
        public JsonResult TangentItems_Update([DataSourceRequest] DataSourceRequest request, [Bind(Prefix = "models")]ICollection<CPTangentItemVM> listItems, int cpNum)
        {
            string sessionKeyString = GenerateSessionKey(cpNum, Enumerations.CpCalculationMethod.TangentList.ToString());
            foreach (var listItem in listItems)
            {
                var sessionKey = GetSessionKey(sessionKeyString, listItem.Id);
                this.SessionStorage.Set(sessionKey, listItem);
            }

            return Json(listItems.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs("Post")]
        public JsonResult TangentItems_Create([DataSourceRequest] DataSourceRequest request, [Bind(Prefix = "models")]ICollection<CPTangentItemVM> listItems, int cpNum)
        {
            int counter = -1;
            string sessionKeyString = GenerateSessionKey(cpNum, Enumerations.CpCalculationMethod.TangentList.ToString());
            foreach (var listItem in listItems)
            {
                listItem.Id = int.Parse($"-{cpNum}{-counter}");
                counter--;
                var sessionKey = GetSessionKey(sessionKeyString, listItem.Id);
                this.SessionStorage.Set(sessionKey, listItem);
            }
            return Json(listItems.ToDataSourceResult(request, ModelState));

        }
        [AcceptVerbs("Post")]


        [AcceptVerbs("Post")]
        public JsonResult TangentItems_Destroy([DataSourceRequest] DataSourceRequest request, [Bind(Prefix = "models")]ICollection<CPTangentItemVM> listItems, int cpNum)
        {
            string sessionKeyString = GenerateSessionKey(cpNum, Enumerations.CpCalculationMethod.TangentList.ToString());
            foreach (var listItem in listItems)
            {
                var sessionKey = GetSessionKey(sessionKeyString, listItem.Id);
                this.SessionStorage.Remove(sessionKey);
            }
            return Json(listItems.ToDataSourceResult(request, ModelState));
        }
        [AcceptVerbs("Post")]
        public JsonResult CurvatureItems_Update([DataSourceRequest] DataSourceRequest request, [Bind(Prefix = "models")]ICollection<CPCurvatureItemVMForKendo> listItems, int cpNum)
        {
            string sessionKeyString = GenerateSessionKey(cpNum, Enumerations.CpCalculationMethod.CurvatureDesign.ToString());
            foreach (var listItem in listItems)

Orbb.Admin/Areas/Orders/Controllers/DetailController.cs
using Microsoft.AspNetCore.Mvc;
using Orbb.Admin.Utility.Mvc;
using Orbb.BL.Interfaces.Orders;
using Orbb.Common.Security;
using Orbb.Data.Models.Models.Orders;
using Orbb.Data.ViewModels.Models.Orders;

namespace Orbb.Admin.Areas.Orders.Controllers
{
    [Area("Orders")]
    [SecuredObject("Orders")]
    public class DetailController : DetailBaseController<Order, OrderVM>
    {

        private IOrderRepository _orderRepository;

        public DetailController(IOrderRepository orderRepository) : base("Order")
        {
            modelIncludes = new string[] { };
            redirectTo = "/Orders/detail/index/{id}";
            OverviewURL = "/Orders/overview";
            _orderRepository = orderRepository;
        }
    }
}

Orbb.Admin/Areas/Orders/Controllers/OverviewController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using Orbb.Admin.Utility.Mvc;
using Orbb.BL.Interfaces.Orders;
using Orbb.Common.Security;
using Orbb.Data.Models.Models.Orders;
using Orbb.Data.Models.Models.Views;
using Orbb.Data.ViewModels.Models.Orders;
using System.Collections.Generic;

namespace Orbb.Admin.Areas.Orders.Controllers
{
    [Area("Orders")]
    [SecuredObject("Orders")]
    public class OverviewController : BaseOverviewController<Order, OrderVM>
    {
        private readonly IOrderRepository _orderRepository;

        public OverviewController(IOrderRepository orderRepository)
        {
            _orderRepository = orderRepository;
        }
        public IActionResult Orders_Overview([DataSourceRequest]DataSourceRequest request)
        {
            IList<OrderView> list = _orderRepository.GetOverview();
            foreach (OrderView ov in list)
            {
                ov.StatusName = stringLocalizer[ov.StatusName];
            }
            ModifyDateFilters(request.Filters, "Date");
            return Json(list.ToDataSourceResult(request));
        }
    }
}

Orbb.Admin/Areas/Countries/Views/Detail/Index.cshtml
@using Kendo.Mvc.UI
@using Orbb.Data.Common
@using Microsoft.Extensions.Localization
@using Orbb.Admin.ViewModels
@using Orbb.Data.ViewModels.Models.Globalization
@using System.Net
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Orbb.Data.ViewModels.Models.Base.CountryVM;
@{

    @inject IStringLocalizer LocString;
    @inject ICurrent<LanguageModel> currentLanguageVM;
    ViewBag.Title = @LocString["G_DETAIL_COUNTRIES"];
    ViewBag.Title2 = LocString["M_COUNTRIES"];
    var currentLanguage = currentLanguageVM?.GetCurrent()?.ShortCode;
    Layout = "/Views/Shared/_Layout.cshtml";
}

@section css {
    @{ await Html.RenderPartialAsync("_UploadPluginCss", false); }
}

<div id="detailHeader">
    <div id="detailHeaderTitle">
        <ul class="detailHeaderBreadcrumbs">
            <li id="detailHeaderIconBreadcrumb-Home"><a href="/"><i class="fas fa-th-large"></i>&nbsp;/</a></li>
            <li id="detailHeaderIconBreadcrumb-Overview"><a href="@Url.Action("Index", "Overview")">@ViewBag.Title2 /</a></li>
            <li><a href="#">@LocString["G_DETAIL"]</a></li>
        </ul>
    </div>
</div>

<div id="detailContainer">
    <div id="commandButtons"></div>

    <form asp-controller="detail" asp-route-area="Countries" asp-action="update" method="post" class="form-horizontal" role="form">
        <div class="detailContainerContentTabBar">

            <ul class="TabBarStyle tabstrip-main">
                <li class="k-state-active" id="tabBarGeneral">
                    @LocString["G_GENERAL"]
                </li>
                <li class="k-state-default" id="tabBarLenssets">
                    @LocString["G_LENSSETS"]
                </li>
            </ul>


            @* Customer details *@
            <div class="detailContainerContentDetails scrollableContent">
                @if (ViewBag.Readonly != "true")
                {
                    <div class="form-group hidden">
                        <input asp-for="@Model.Id" />
                    </div>
                }
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="col-sm-12 control-label changeRequest">@LocString["G_NAME"]</label>
                            <div class="col-sm-9">
                                <input asp-for="@Model.Description" class="form-control" />
                                <span asp-validation-for="@Model.Description"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            @* Lens sets*@
            <div class="detailContainerContent scrollableContent">
                <div class="form-group hidden" id="UsedLenssets">
                    @if (Model.AvailableLenssets != null)
                    {
                        foreach (var lensset in Model.AvailableLenssets)
                        {
                            <input class="initialLensset" value="@lensset.Id" />
                        }
                    }
                </div>
                
                @(Html.Kendo().Grid<Orbb.Data.ViewModels.Models.Customers.LenssetVM>()
                    .Name("grid").HtmlAttributes(new { @class = "overviewGrid" })
                    .Columns(columns =>
                    {
                        columns.Select().Width(20);
                        columns.Bound(p => p.Name).Title(@LocString["G_NAME"]).Width(200).Filterable(ftb => ftb.Cell(cell => cell.Operator("contains")));
                        columns.Bound(p => p.TypeName).Title(@LocString["G_TYPE"]).Width(200).Filterable(ftb => ftb.Cell(cell => cell.Operator("contains")));
                        columns.Bound(p => p.LensDiameter).Title(@LocString["G_DIAMETER"]).Width(200).Filterable(ftb => ftb.Cell(cell => cell.Operator("eq")));
                        columns.Bound(p => p.Supplier).Title(@LocString["G_SUPPLIER"]).Width(200).Filterable(ftb => ftb.Cell(cell => cell.Operator("contains")));
                    })
                    .Pageable()
                    .PersistSelection()
                    .Sortable()
                    .Events(events => events
                        .DataBound("onDataBound")
                        .Change("onChange")
                    )
                    .Filterable(ftb => ftb.Mode(GridFilterMode.Row))
                    .DataSource(datasource => datasource
                        .Ajax()
                        .Batch(true)
                        .PageSize(15)
                        .ServerOperation(false)
                        .Events(events => events.Error("error_handler"))
                        .Model(model =>
                        {
                            model.Id(p => p.Id);
                            model.Field(p => p.Name);
                            model.Field(p => p.Type);
                            model.Field(p => p.TypeName);
                            model.Field(p => p.LensDiameter);
                            model.Field(p => p.Supplier);
                        })
                        .Read(read => read.Action("GetLensesForCountry", "Data", new { Area = "", countryId = Model.Id }))
                        .Sort(sort => sort.Add("Name").Ascending())
                    )
                    .Deferred()
                )
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_UploadPluginScripts", false); }

    <environment names="Development">
        <script src="~/js/kendoGridSizing.js"></script>
        <script src="~/js/Countries/countries.detail.js"></script>
        @if (ViewBag.Readonly != "true")
        {
            <script src="~/js/core/custom.form.change.js"></script>
        }
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/kendoGridSizing.js" asp-append-version="true"></script>
        <script src="~/js/Countries/countries.detail.min.js" asp-append-version="true"></script>
        @if (ViewBag.Readonly != "true")
        {
            <script src="~/js/core/custom.form.change.min.js" asp-append-version="true"></script>
        }
    </environment>
}