Orbb.Admin/Areas/Security/Controllers/UserGroupDetailController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using Orbb.Admin.Utility.Mvc;
using Orbb.BL.Interfaces.General;
using Orbb.BL.Interfaces.Security;
using Orbb.Common.Security;
using Orbb.Data.Models.Models.Security;
using Orbb.Data.ViewModels.Models.Security;

namespace Orbb.Admin.Areas.Security.Controllers
{
    [Area("Security")]
    [SecuredObject("Usergroups")]
    public class UserGroupDetailController : DetailBaseController<UserGroup, UserGroupDetailVM>
    {
        private readonly IUserGroupsRepository userGroupsRepository;

        public UserGroupDetailController(ILookupProvider lookupProvider, IDataService dataService, IUserGroupsRepository userGroupsRepository)
        {
            modelIncludes = new[] { "Permissions" };
            redirectTo = "/security/usergroups";
            LookupProvider = lookupProvider;
            DataService = dataService;
            this.userGroupsRepository = userGroupsRepository;
        }

        public override void BeforeLoad(int id = 0)
        {
            if (id > 0) userGroupsRepository.CreateUserGroupObjectPermissions(id);
            base.BeforeLoad(id);
        }

        public IActionResult UserGroupPermissions_Read([DataSourceRequest]DataSourceRequest request)
        {
            return Json(userGroupsRepository.GetUserGroupsOverview().ToDataSourceResult(request));
        }
    }
}

Orbb.Admin/Areas/Security/Views/UserGroupDetail/Index.cshtml
@using Orbb.Data.ViewModels.Models.Security
@using Kendo.Mvc.UI
@using Microsoft.Extensions.Localization
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Orbb.Data.ViewModels.Models.Security.UserGroupDetailVM
@{
    @inject IStringLocalizer LocString;

    Layout = "/Views/Shared/_Layout.cshtml";
    ViewBag.Title = LocString["G_DETAIL_USERGROUP"];
    ViewBag.Title2 = LocString["M_SECURITY"];
    ViewBag.Title3 = LocString["M_USERGROUPS"];
    ViewBag.Title4 = LocString["G_DETAIL"];
}

<div id="detailHeader">
    <div id="detailHeaderTitle">
        <ul class="detailHeaderBreadcrumbs">
            <li id="detailHeaderIconBreadcrumb-Home"><a href="/"><i class="fas fa-th-large"></i>&nbsp;/</a></li>
            <li id="detailHeaderIconBreadcrumb-Security"><a href="/security/menu/">@ViewBag.Title2 /</a></li>
            <li id="detailHeaderIconBreadcrumb-Usergroups"><a href="/security/usergroups/">@ViewBag.Title3 /</a></li>
            <li><a href="#">@ViewBag.Title4</a></li>
        </ul>
    </div>
</div>

<div id="detailContainer">
    <form asp-controller="UserGroupDetail" asp-route-area="Security" asp-action="Update" method="post" class="form-horizontal" role="form">
        <div class="detailContainerContentTabBar">

            <ul class="TabBarStyle tabstrip-main">
                <li class="k-state-active" id="tabBarGeneral">
                    @LocString["G_GENERAL"]
                </li>
                <li>
                    @LocString["G_RIGHTS"]
                </li>
            </ul>


            <div class="detailContainerContentDetails">
                @if (ViewBag.Readonly != "true")
                {
                    <div class="form-group hidden">
                        <label asp-for="@Model.Id" class="col-sm-12 control-label"></label>
                        <div class="col-sm-9">
                            <input asp-for="@Model.Id" class="form-control" name="Id" id="Id" value="@Model.Id" />
                            <span asp-validation-for="@Model.Id" class="text-danger"></span>
                        </div>
                    </div>
                }
                <div>
                    @*<div asp-validation-summary="All" class="text-danger"></div>*@
                </div>
                <div class="row">
                    <div class="col-sm-5">
                        <div class="form-group">
                            <label class="col-sm-12 control-label">@LocString["G_DESCRIPTION"]</label>
                            <div class="col-sm-9">
                                <input asp-for="@Model.Description" class="form-control" name="Description" id="Description" value="@Model.Description" />
                                <span asp-validation-for="@Model.Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-5">


                    </div>
                </div>

            </div>

            <div class="detailContainerContentDetails calculateContainerSize">
                @(Html.Kendo().Grid<SecuredObjectPermissionVm>(Model.Permissions)
                        .Name("permissionsGrid")
                        .Columns(columns =>
                        {
                            columns.Bound(p => p.Id).Hidden().ClientTemplate("#= Id #" +
                            "<input type='hidden' name='Permissions[#= index(data)#].Id' value='#= Id #' />"
                            );
                            //columns.Bound(p => p.SecuredObject.Object);
                            columns.Bound(p => p.SecuredObjectId).Hidden().ClientTemplate("#= SecuredObjectId #" +
                            "<input type='hidden' name='Permissions[#= index(data)#].SecuredObjectId' value='#= SecuredObjectId #' />"
                            );
                            columns.Bound(p => p.UserGroupId).Hidden().ClientTemplate("#= UserGroupId #" +
                            "<input type='hidden' name='Permissions[#= index(data)#].UserGroupId' value='#= UserGroupId #' />"
                            );

                            columns.Bound(p => p.SecuredObjectObject).Title(LocString["G_NAME"]).ClientTemplate("#= SecuredObjectObject #" +
                        "<input type='hidden' name='Permissions[#= index(data)#].SecuredObjectObject' value='#= SecuredObjectObject #' />"
                        );
                            columns.Bound(p => p.Add).ClientTemplate("#= Add #" +
                        "<input type='hidden' name='Permissions[#= index(data)#].Add' value='#= Add #' />"
                        );
                            columns.Bound(p => p.Delete).ClientTemplate("#= Delete #" +
                        "<input type='hidden' name='Permissions[#= index(data)#].Delete' value='#= Delete #' />"
                        );
                            columns.Bound(p => p.Read).ClientTemplate("#= Read #" +
                        "<input type='hidden' name='Permissions[#= index(data)#].Read' value='#= Read #' />"
                        );
                            columns.Bound(p => p.Update).ClientTemplate("#= Update #" +
                        "<input type='hidden' name='Permissions[#= index(data)#].Update' value='#= Update #' />"
                        );
                        })
                        .Events(events => events.Save("gridRowChanged"))
                        .Selectable(selectable => selectable.Mode(GridSelectionMode.Single))
                        .Editable(editable => editable.Mode(GridEditMode.InCell))

                        .Sortable()
                        //.Navigatable()
                        .Scrollable()
                        .DataSource(dataSource => dataSource
                        .Ajax()
                        .Batch(true)
                        .Model(model =>
                        {
                            model.Id(p => p.Id); // Specify the property which is the unique identifier of the model
                            model.Field(p => p.Id).Editable(false); // Make the Id property not editable
                            model.Field(p => p.SecuredObjectId).Editable(false);
                            model.Field(p => p.SecuredObjectObject).Editable(false);
                        })
                        .ServerOperation(false)

                        .Events(events => events.Error("error_handler"))
                       //.Read(read => read.Action("Addresses_Read", "Detail", new { id = Model.Id }))
                       //.Create(create => create.Action("Addresses_Create", "Detail")

                       )
                       .Deferred()
                )
            </div>
        </div>
    </form>
</div>


@section Scripts {
<environment names="Development">
    <script src="~/js/security/security.usergroups.layout.js"></script>
    @if (ViewBag.Readonly != "true")
    {
        <script src="~/js/core/custom.form.change.js"></script>
    }
</environment>
<environment names="Staging,Production">
    <script src="~/js/security/security.usergroups.layout.min.js" asp-append-version="true"></script>
    @if (ViewBag.Readonly != "true")
    {
        <script src="~/js/core/custom.form.change.min.js" asp-append-version="true"></script>
    }
</environment>
}