Orbb.Admin/Areas/Security/Controllers/UserDetailController.cs
using Microsoft.AspNetCore.Mvc;
using Orbb.Admin.Utility.Mvc;
using Orbb.BL.Interfaces.General;
using Orbb.BL.Interfaces.Security;
using Orbb.Common.Security;
using Orbb.Data.Models.Models.Security;
using Orbb.Data.ViewModels.Models.Security;

namespace Orbb.Admin.Areas.Security.Controllers
{
    [Area("Security")]
    [SecuredObject("Users")]
    public class UserDetailController : DetailBaseController<User, UserDetailVm>
    {
        private readonly IUserRepository userRepository;

        public UserDetailController(ILookupProvider lookupProvider, IDataService dataService, IUserRepository userRepository) : base("SystemUser")
        {
            modelIncludes = new[] { "UserGroup" };
            redirectTo = "/security/users";
            LookupProvider = lookupProvider;
            DataService = dataService;
            this.userRepository = userRepository;
        }

        public override UserDetailVm BeforeUpdate(UserDetailVm model)
        {
            // set hash if new user
            if (model.Id <= 0)
            {
                var hashSalt = new StringHash().Hash(model.Password);
                model.Password = hashSalt.Hash;
                model.Salt = hashSalt.Salt;
            }
            else if (model.Password != model.OldPassword)
            {
                var hash = new StringHash().HashWithSalt(model.Password, model.Salt);
                model.Password = hash;
            }

            return base.BeforeUpdate(model);
        }

        public override void LoadViewBagData(int id = 0)
        {
            base.LoadViewBagData(id);

            ViewBag.UserGroups = LookupProvider.GetUserGroupsList();
            ViewBag.UserTypes = LookupProvider.GetUserTypesForCombobox();
            ViewBag.PartialLanguages = LookupProvider.GetLanguageTranslationsMenuList();
        }


        public IActionResult DeleteUser(UserDetailVm model)
        {
            redirectTo = "/security/users";
            return Delete(new UserDetailVm() { Id = model.Id });
        }
    }
}

Orbb.Admin/Areas/Security/Views/UserDetail/Index.cshtml
@using Orbb.Data.Common
@using Orbb.Data.Models.Models.Security
@using Microsoft.Extensions.Localization
@using Orbb.Admin.ViewModels;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Orbb.Data.ViewModels.Models.Security.UserDetailVm

@{
    @inject IStringLocalizer LocString;
    @inject ICurrent<LanguageModel> currentLanguageVM;
    var currentLanguage = currentLanguageVM?.GetCurrent()?.ShortCode;
    ViewBag.Title = LocString["G_DETAIL_USER"];
    ViewBag.Title2 = LocString["M_SECURITY"];
    ViewBag.Title3 = LocString["M_USERS"];
    ViewBag.Title4 = LocString["G_DETAIL"];

    Layout = "/Views/Shared/_Layout.cshtml";
}

<div class="modal fade" id="modalEditCredentials" tabindex="-1" role="dialog" aria-labelledby="modalImport" aria-hidden="true">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span><span class="sr-only">@LocString["G_CLOSE"]</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">@LocString["SEC_EDITCREDENTIALS"]</h4>
                </div>
                <div id="modalEditCredentialsBody" class="modal-body">
                    <div class="importfeedback"></div>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-primary grow CloseModalOnClick popupCancelButton" />
                    <input type="button" class="btn btn-default grow" onclick="submitCredentials()" id="popupStoreButton" />
                </div>
            </div>
        </div>
    </div>
</div>

<div id="detailHeader">
    <div id="detailHeaderTitle">
        <ul class="detailHeaderBreadcrumbs">
            <li id="detailHeaderIconBreadcrumb-Home"><a href="/"><i class="fas fa-th-large"></i>&nbsp;/</a></li>
            <li id="detailHeaderIconBreadcrumb-Security"><a href="/security/menu/">@ViewBag.Title2 /</a></li>
            <li id="detailHeaderIconBreadcrumb-Users"><a href="/security/users/">@ViewBag.Title3 /</a></li>
            <li><a href="#">@ViewBag.Title4</a></li>
        </ul>
    </div>
</div>
<div id="detailContainer">

    <div id="commandButtons"></div>
    <form asp-controller="UserDetail" asp-route-area="Security" asp-action="Update" method="post" class="form-horizontal" role="form">
        <div class="detailContainerContentTabBar">

            <ul class="TabBarStyle tabstrip-main">
                <li class="k-state-active" id="tabBarGeneral">
                    @LocString["G_GENERAL"]
                </li>
            </ul>

            <div class="detailContainerContentDetails fixedheight101">
                @if (ViewBag.Readonly != "true")
                {
                    <div class="form-group hidden">
                        <label asp-for="@Model.Id" class="col-sm-12 control-label"></label>
                        <div class="col-sm-9">
                            <input asp-for="@Model.Id" class="form-control" name="Id" id="Id" value="@Model.Id" />
                            <span asp-validation-for="@Model.Id" class="text-danger"></span>
                        </div>
                    </div>
                }
                <div>
                    @*<div asp-validation-summary="All" class="text-danger"></div>*@
                </div>
                <div class="row">
                    <div class="col-sm-5">
                        <div class="form-group">
                            <label class="col-sm-12 control-label">@LocString["G_FIRSTNAME"]</label>
                            <div class="col-sm-9">
                                <input asp-for="@Model.FirstName" class="form-control" name="FirstName" id="FirstName" value="@Model.FirstName" />
                                <span asp-validation-for="@Model.FirstName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-12 control-label">@LocString["G_LASTNAME"]</label>
                            <div class="col-sm-9">
                                <input asp-for="@Model.LastName" class="form-control" name="LastName" id="LastName" value="@Model.LastName" />
                                <span asp-validation-for="@Model.LastName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-12 control-label">@LocString["CUSU_EMAIL"]</label>
                            <div class="col-sm-9">
                                <input asp-for="@Model.EmailAddress" class="form-control" autocomplete="false" name="EmailAdress" id="EmailAddress" value="@Model.EmailAddress" />
                                <span asp-validation-for="@Model.EmailAddress" class="text-danger"></span>
                            </div>
                        </div>
                        @if (Model.Id == 0)
                        {
                            <div class="form-group">
                                <label class="col-sm-12 control-label changeRequest">@LocString["LN_USERNAME"] </label>
                                <div class="col-sm-9">
                                    <input asp-for="@Model.UserName" class="form-control username" name="UserName" id="UserName" value="@Model.UserName" autocomplete='new-password' />
                                    <span asp-validation-for="@Model.UserName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-12 control-label changeRequest">@LocString["LN_PASSWORD"] </label>
                                <div class="col-sm-9">
                                    <input asp-for="@Model.Password" type="password" class="form-control password" name="Password" id="Password" value="@Model.Password" autocomplete='new-password' />
                                    <span asp-validation-for="@Model.Password" class="text-danger"></span>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="form-group">
                                <label class="col-sm-12 control-label changeRequest">@LocString["LN_USERNAME"] <span class="Icon fa fa-lock requestIcon"></span></label>
                                <div class="col-sm-9">
                                    <input asp-for="@Model.UserName" class="form-control username" readonly name="UserName" id="UserName" value="@Model.UserName" />
                                    <span asp-validation-for="@Model.UserName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-12 control-label changeRequest">@LocString["LN_PASSWORD"] <span class="Icon fa fa-lock requestIcon"></span></label>
                                <div class="col-sm-9">
                                    <input asp-for="@Model.Password" type="password" class="form-control password" readonly name="Password" id="Password" value="@Model.Password" />
                                    <span asp-validation-for="@Model.Password" class="text-danger"></span>
                                </div>
                            </div>
                            @Html.HiddenFor(m => m.Salt)
                            @Html.Hidden("OldPassword", Model.Password, new { @id = "OldPassword" })
                        }
                        <div class="form-group">
                            <label class="col-sm-12 control-label">@LocString["CUSU_USERGROUP"]</label>
                            <div class="col-sm-9">
                                <select id="UserGroupId" name="UserGroupId" class="form-control" style="width: 100%;">
                                    @foreach (UserGroup item in ViewBag.UserGroups)
                                    {
                                        if (@Model.UserGroupId == item.Id)
                                        {
                                            <option class="dropdown" value="@item.Id" selected>@item.Description</option>
                                        }
                                        else
                                        {
                                            <option class="dropdown" value="@item.Id">@item.Description</option>
                                        }
                                    }
                                </select>
                                <span asp-validation-for="@Model.UserGroupId" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-12 control-label">@LocString["G_USERTYPE"]</label>
                            <div class="col-sm-9">
                                <select id="TypeId" name="TypeId" class="form-control" style="width: 100%;">
                                    @foreach (var item in ViewBag.UserTypes)
                                    {
                                        var selected = @Model.TypeId == item.Id ? "selected" : "";
                                        <option class="dropdown" value="@item.Id" @selected>@item.Text</option>
                                    }
                                </select>

                                <span asp-validation-for="@Model.TypeId" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.HiddenFor(m => m.LanguageId, new { id = "hdnLanguageID" })
                            <label class="col-sm-12 control-label">@LocString["CUSU_LANGUAGE"]</label>
                            <div class="col-sm-9">
                                <select id="userLanguageId" name="userLanguageId" class="form-control" style="width: 100%;">

                                    @foreach (var item in ViewBag.PartialLanguages)
                                    {
                                        if (item.ShortCode == @currentLanguage)
                                        {
                                            if (@Model.LanguageId == item.LanguageId)
                                            {
                                                <option class="dropdown" value="@item.LanguageId" selected>@item.Value</option>
                                            }
                                            else
                                            {
                                                <option class="dropdown" value="@item.LanguageId">@item.Value</option>
                                            }
                                        }
                                    }
                                </select>
                                @*<span asp-validation-for="@Model.LanguageId" class="text-danger"></span>*@
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-5">
                    </div>
                </div>
            </div>

            <div class="detailContainerContentDetails"></div>
            <div class="detailContainerContentDetails"></div>
            <div class="detailContainerContentDetails"></div>

        </div>
    </form>
</div>

@section Scripts {
    <environment names="Development">
        @if (ViewBag.Readonly != "true")
        {
            if (ViewBag.Readonly != "true")
            {
                <script src="~/js/core/custom.form.change.js"></script>
            }
            <script src="~/js/security/security.userdetail.js"></script>
        }

    </environment>
    <environment names="Staging,Production">
        @if (ViewBag.Readonly != "true")
        {
            if (ViewBag.Readonly != "true")
            {
            <script src="~/js/core/custom.form.change.min.js" asp-append-version="true"></script>
            }
            <script src="~/js/security/security.userdetail.min.js" asp-append-version="true"></script>
        }
    </environment>
}